[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    https://github.com/T-vK/ESP32-BLE-Mouse.git


; ESP32 Dev Board
; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; ; board = esp32-c3-devkitm-1
; framework = arduino
; monitor_speed = 115200
; upload_speed = 115200
; build_flags =
;     ; -D ARDUINO_USB_MODE=1 
;     ; -D ARDUINO_USB_CDC_ON_BOOT=1

; ; Pull in NimBLE-Arduino (v2.1.0 or newer)
; lib_deps =
;   h2zero/NimBLE-Arduino@^2.1.0